name: Deploy to S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Deploy Frontend to S3
      run: |
        cd Frontend
        aws s3 sync . s3://vibesheets-frontend-prod \
          --delete \
          --exclude "*.DS_Store"
        
        aws s3 cp index.html s3://vibesheets-frontend-prod/index.html \
          --content-type "text/html" \
          --metadata-directive REPLACE
          
        aws s3 cp dashboard.html s3://vibesheets-frontend-prod/dashboard.html \
          --content-type "text/html" \
          --metadata-directive REPLACE
        
        aws s3 sync assets/css/ s3://vibesheets-frontend-prod/assets/css/ \
          --content-type "text/css" \
          --metadata-directive REPLACE
          
        aws s3 sync assets/js/ s3://vibesheets-frontend-prod/assets/js/ \
          --content-type "application/javascript" \
          --metadata-directive REPLACE
          
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"