name: 🔒 Security Audit

on:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Mondays
  push:
    branches: [main, master]
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'Backend/Terraform/**'
  workflow_dispatch:

jobs:
  frontend-security:
    name: 🎨 Frontend Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📋 Install Dependencies
        run: npm ci

      - name: 🔍 NPM Audit
        run: npm audit --audit-level moderate

      - name: 🛡️ CodeQL Analysis
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: 🏗️ Build for Analysis
        run: npm run build

      - name: 📊 CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  infrastructure-security:
    name: 🏗️ Infrastructure Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔧 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.6.0'

      - name: 🚀 Terraform Init
        run: terraform init -backend=false
        working-directory: ./Backend/Terraform

      - name: 🛡️ TFSec Security Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: Backend/Terraform

      - name: 🔒 Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: Backend/Terraform
          framework: terraform

  dependency-review:
    name: 📦 Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔍 Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate